name: Spawners
description: Only a simple spawners plugin.
version: 1.0
api-version: 1.8
author: zPedroo_
main: com.zpedroo.voltzspawners.VoltzSpawners
depend: [HolographicDisplays, MultiEconomy, ProtocolLib, PlotSquared, mcMMO]
load: POSTWORLD
commands:
  spawners:
    aliases: [spawner, mobspawner, mobspawners]